class Categories:
    
    def __init__(self):
        
        self.columns = {'stats':      ['aerA', 'hdrsW', 'blk', 'clr', 'tckC',
                                       'presA', 'presC', 'interceptions', 'sprints',
                                       'possLost', 'possWon', 'drb', 'opCrsA', 'opCrsC',
                                       'psA', 'psC', 'prPasses', 'opKp', 'chC', 'xa',
                                       'shot', 'sht', 'npXg'],
                        'attributes': ['cor', 'cro', 'dri', 'fin', 'fir',
                                       'fre', 'hea', 'lon', 'lth', 'mar', 
                                       'pas', 'pen', 'tck', 'tec', 'agg',
                                       'ant', 'bra', 'cmp', 'cnt', 'decisions',
                                       'det', 'fla', 'ldr', 'otb', 'pos', 
                                       'tea', 'vis', 'wor', 'acc', 'agi',
                                       'bal', 'jum', 'natF', 'pac', 'sta',
                                       'str', 'aer', 'cmd', 'com', 'ecc',
                                       'han', 'kic', 'oneVsOne', 'pun',
                                       'ref', 'tro', 'thr'],
                        'contract':   ['club', 'beginDate', 'expiryDate',
                                       'extension', 'wage', 'value', 'releaseClauseFee']}
        
        self.stats = {'def': ['aerA', 'hdrsW', 'blk', 'clr', 'tckC',
                         'presA', 'presC', 'interceptions', 'sprints',
                         'possLost', 'possWon'],
                 'off': ['hdrsW', 'drb', 'opCrsA', 'opCrsC',
                         'psA', 'psC', 'prPasses', 'opKp', 'chC', 'xa',
                         'shot', 'sht', 'npXg'],
                 'WB':  ['presC', 'interceptions', 'sprints',
                         'possWon', 'drb', 'opCrsC', 'psC',
                         'prPasses', 'opKp', 'xa'],
                 'BW':  ['aerA', 'hdrsW', 'tckC', 'presA',
                         'presC', 'interceptions', 'possWon'],
                 'DC':  ['hdrsW', 'blk', 'clr', 'tckC', 'interceptions',
                         'possLost', 'possWon', 'psC', 'prPasses'],
                 'DM':  ['hdrsW', 'blk', 'clr', 'tckC', 'presC', 'sprints',
                         'possWon', 'psC', 'prPasses', 'xa'],
                 'MC':  ['presC', 'possWon', 'psC', 'prPasses',
                         'opKp', 'chC', 'xa'],
                 'AM':  ['drb', 'opCrsA', 'opCrsC', 'prPasses', 'opKp',
                         'xa', 'shot', 'sht', 'npXg'],
                 'STC':  ['hdrsW', 'tckC', 'presC', 'interceptions', 'psC', 'opKp',
                         'xa', 'shot', 'sht', 'npXg'],
                 'all': ['aerA', 'hdrsW', 'blk', 'clr', 'tckC',
                         'presA', 'presC', 'interceptions', 'sprints',
                         'possLost', 'possWon', 'drb', 'opCrsA', 'opCrsC',
                         'psA', 'psC', 'prPasses', 'opKp', 'chC', 'xa',
                         'shot', 'sht', 'npXg']}
    
        self.playerInfo =  {'all': ['age', 'mins', 'position', 'allPositions', 'division', 'rightFoot', 'leftFoot', 'club', 'nat'],
                            'index': ['age', 'mins', 'division', 'rightFoot', 'leftFoot', 'club', 'nat']}
        
        self.contract = {'all':   ['beginDate', 'expiryDate',
                                   'extension', 'wage', 'value', 'releaseClauseFee']}
        
        self.ca = {'ca': ['ca']}
        
        self.attributes = {'WB': ['cro', 'dri', 'fir', 'pas', 'tck',
                                  'tec', 'ant', 'det', 'decisions',
                                  'fla', 'otb', 'pos', 'tea', 'vis',
                                  'wor', 'acc', 'natF', 'pac', 'sta'],
                           'DC': ['hea', 'mar', 'pas', 'tck', 'agg',
                                  'ant', 'bra', 'cmp', 'cnt', 'decisions',
                                  'det', 'pos', 'tea', 'vis', 'wor', 'acc',
                                  'jum', 'natF', 'pac', 'sta', 'str'],
                           'DM': ['fir', 'hea', 'mar', 'pas',
                                  'tck', 'tec', 'agg', 'ant', 'bra',
                                  'cmp', 'cnt', 'decisions', 'det',
                                  'otb', 'pos', 'tea', 'vis', 'wor',
                                  'jum', 'sta', 'str'],
                           'MC': ['dri', 'fir', 'mar', 'pas',
                                  'tck', 'tec', 'ant', 'cmp',
                                  'cnt', 'decisions', 'det',
                                  'fla', 'otb', 'pos', 'tea',
                                  'vis', 'wor', 'acc', 'agi',
                                  'bal', 'natF', 'pac', 'sta'],
                           'AM': ['dri', 'fin', 'fir', 'pas',
                                  'tck', 'tec', 'ant', 'decisions',
                                  'det', 'fla', 'otb', 'tea',
                                  'vis', 'wor', 'acc', 'agi',
                                  'bal', 'natF', 'pac', 'sta',],
                           'STC': ['dri', 'fin', 'fir', 'pas',
                                   'tec', 'agg', 'ant', 'bra',
                                   'cmp', 'cnt', 'decisions', 'det',
                                   'fla', 'otb', 'tea', 'vis',
                                   'wor', 'acc', 'agi', 'bal',
                                   'jum', 'natF', 'pac', 'sta', 'str']}
        
        self.tables = {'name': 'player', 'playerID': 'player', 'age': 'player_info', 'position': 'player_info',
                       'allPositions': 'player_info', 'rightFoot': 'player_info', 'leftFoot': 'player_info',
                       'mins': 'player_info', 'division': 'player_info',
                       'club': 'player_info', 'nat': 'player_info',
                       'eligible': 'player_info', 'season': 'player_info',
                       'aerA': 'stats', 'hdrsW': 'stats', 'blk': 'stats',
                       'clr': 'stats', 'tckC': 'stats', 'presA': 'stats',
                       'presC': 'stats', 'interceptions': 'stats',
                       'sprints': 'stats', 'possLost': 'stats',
                       'possWon': 'stats', 'drb': 'stats', 'opCrsA': 'stats',
                       'opCrsC': 'stats', 'psA': 'stats', 'psC': 'stats',
                       'prPasses': 'stats', 'opKp': 'stats', 'chC': 'stats',
                       'xa': 'stats', 'shot': 'stats', 'sht': 'stats', 'npXg': 'stats',
                       'club': 'contract', 'beginDate': 'contract', 'expiryDate': 'contract',
                       'extension': 'contract', 'wage': 'contract', 'value': 'contract', 'releaseClauseFee': 'contract',
                       'cor': 'attributes', 'cro': 'attributes', 'dri': 'attributes',
                       'fin': 'attributes','fir': 'attributes', 'fre': 'attributes',
                       'hea': 'attributes', 'lon': 'attributes', 'lth': 'attributes',
                       'mar': 'attributes', 'pas': 'attributes', 'pen': 'attributes',
                       'tck': 'attributes', 'tec': 'attributes', 'agg': 'attributes',
                       'ant': 'attributes', 'bra': 'attributes', 'cmp': 'attributes',
                       'cnt': 'attributes', 'decisions': 'attributes', 'det': 'attributes',
                       'fla': 'attributes', 'ldr': 'attributes', 'otb': 'attributes',
                       'pos':'attributes', 'tea': 'attributes', 'vis': 'attributes',
                       'wor': 'attributes', 'acc': 'attributes', 'agi': 'attributes',
                       'bal': 'attributes', 'jum': 'attributes', 'natF': 'attributes',
                       'pac': 'attributes', 'sta': 'attributes', 'str': 'attributes',
                       'aer': 'attributes', 'cmd': 'attributes', 'com': 'attributes',
                       'ecc': 'attributes', 'han': 'attributes', 'kic': 'attributes',
                       'oneVsOne': 'attributes', 'pun': 'attributes', 'ref': 'attributes',
                       'tro': 'attributes', 'thr': 'attributes',
                       'ca': 'ca'}
